<?php
/*
Plugin Name: WP Disallow Root Control
Plugin URI: https://example.com/wp-disallow-root-control
Description: Disallow access to the root directory via robots.txt with an option to enable or disable.
Version: 1.0.0
Author: Algorithus Pvt. Ltd.
Author URI: https://algorithus.com
License: GPLv2 or later
Text Domain: wp-disallow-root-control
*/

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

// Add settings to the "Reading" settings page
function wpdrc_register_settings() {
    add_settings_section(
        'wpdrc_settings_section', // Section ID
        __( 'Disallow Root Control', 'wp-disallow-root-control' ), // Section Title with translation
        'wpdrc_section_callback', // Callback function to output the section description
        'reading' // The settings page to display the section
    );

    add_settings_field(
        'wpdrc_enable_disallow', // Field ID
        __( 'Enable Disallow Root in Robots.txt', 'wp-disallow-root-control' ), // Field Title with translation
        'wpdrc_enable_disallow_callback', // Callback function to output the field
        'reading', // The settings page to display the field
        'wpdrc_settings_section' // The section to display the field
    );

    register_setting( 'reading', 'wpdrc_enable_disallow', array(
        'type' => 'boolean',
        'description' => __( 'Enable disallowing the root directory in robots.txt', 'wp-disallow-root-control' ),
        'sanitize_callback' => 'wpdrc_sanitize_checkbox',
        'default' => false,
    ) );
}
add_action( 'admin_init', 'wpdrc_register_settings' );

// Output the section description
function wpdrc_section_callback() {
    echo '<p>' . esc_html__( 'Control access to the root directory in the robots.txt file.', 'wp-disallow-root-control' ) . '</p>';
}

// Output the field
function wpdrc_enable_disallow_callback() {
    $option = get_option( 'wpdrc_enable_disallow' );
    ?>
    <input type="checkbox" name="wpdrc_enable_disallow" value="1" <?php checked( 1, $option ); ?> />
    <label for="wpdrc_enable_disallow"><?php esc_html_e( 'Enable disallowing the root directory in robots.txt', 'wp-disallow-root-control' ); ?></label>
    <?php
}

// Sanitize the checkbox input
function wpdrc_sanitize_checkbox( $input ) {
    return ( $input === '1' ) ? 1 : 0;
}

// Generate robots.txt content based on the setting
function wpdrc_generate_robots_txt() {
    $enable_disallow = get_option( 'wpdrc_enable_disallow' );

    if ( $enable_disallow ) {
        $robots_txt = "User-agent: *\n";
        $robots_txt .= "Disallow: /\n";
        $robots_txt .= "Allow: /wp-admin/admin-ajax.php\n";

        status_header( 200 );
        header( 'Content-Type: text/plain; charset=utf-8' );
        echo "<!-- Robots.txt generated by WP Disallow Root Control plugin -->\n";
        echo esc_html( $robots_txt );
        exit;
    }
}
add_action( 'do_robotstxt', 'wpdrc_generate_robots_txt' );
